spring.application.name=todo_backend

spring.datasource.url=jdbc:postgresql://postgres:5432/todo_db
spring.datasource.username=postgres
spring.datasource.password=Appleman6254!

# JPA / Hibernate inställningar
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO